#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_HitNotifySoundLibraryComponent

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_HitNotifySoundLibraryComponent.BP_HitNotifySoundLibraryComponent_C
// 0x0000 (0x0188 - 0x0188)
class UBP_HitNotifySoundLibraryComponent_C : public UFortHitNotifySoundLibraryComponent
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_HitNotifySoundLibraryComponent_C">();
	}
	static class UBP_HitNotifySoundLibraryComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_HitNotifySoundLibraryComponent_C>();
	}
};

}

