#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPS26_AboutModal_Pip

#include "Basic.hpp"

#include "BPS26_AboutModal_Pip_classes.hpp"
#include "BPS26_AboutModal_Pip_parameters.hpp"


namespace SDK
{

// Function BPS26_AboutModal_Pip.BPS26_AboutModal_Pip_C.BP_OnClicked
// (Event, Protected, BlueprintEvent)

void UBPS26_AboutModal_Pip_C::BP_OnClicked()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS26_AboutModal_Pip_C", "BP_OnClicked");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS26_AboutModal_Pip.BPS26_AboutModal_Pip_C.BP_OnHovered
// (Event, Protected, BlueprintEvent)

void UBPS26_AboutModal_Pip_C::BP_OnHovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS26_AboutModal_Pip_C", "BP_OnHovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS26_AboutModal_Pip.BPS26_AboutModal_Pip_C.BP_OnUnhovered
// (Event, Protected, BlueprintEvent)

void UBPS26_AboutModal_Pip_C::BP_OnUnhovered()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS26_AboutModal_Pip_C", "BP_OnUnhovered");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS26_AboutModal_Pip.BPS26_AboutModal_Pip_C.ExecuteUbergraph_BPS26_AboutModal_Pip
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS26_AboutModal_Pip_C::ExecuteUbergraph_BPS26_AboutModal_Pip(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS26_AboutModal_Pip_C", "ExecuteUbergraph_BPS26_AboutModal_Pip");

	Params::BPS26_AboutModal_Pip_C_ExecuteUbergraph_BPS26_AboutModal_Pip Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BPS26_AboutModal_Pip.BPS26_AboutModal_Pip_C.Is Focused
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Is_Focused_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS26_AboutModal_Pip_C::Is_Focused(bool Is_Focused_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS26_AboutModal_Pip_C", "Is Focused");

	Params::BPS26_AboutModal_Pip_C_Is_Focused Parms{};

	Parms.Is_Focused_0 = Is_Focused_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

