#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPS26_CustomizationScreen

#include "Basic.hpp"

#include "BPS26_CustomizationScreen_classes.hpp"
#include "BPS26_CustomizationScreen_parameters.hpp"


namespace SDK
{

// Function BPS26_CustomizationScreen.BPS26_CustomizationScreen_C.BP_OnActivated
// (Event, Protected, BlueprintEvent)

void UBPS26_CustomizationScreen_C::BP_OnActivated()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS26_CustomizationScreen_C", "BP_OnActivated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BPS26_CustomizationScreen.BPS26_CustomizationScreen_C.ExecuteUbergraph_BPS26_CustomizationScreen
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPS26_CustomizationScreen_C::ExecuteUbergraph_BPS26_CustomizationScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BPS26_CustomizationScreen_C", "ExecuteUbergraph_BPS26_CustomizationScreen");

	Params::BPS26_CustomizationScreen_C_ExecuteUbergraph_BPS26_CustomizationScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

