#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPS26_BattlePassTileEmpty

#include "Basic.hpp"

#include "BattlePassBase_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BPS26_BattlePassTileEmpty.BPS26_BattlePassTileEmpty_C
// 0x0000 (0x15F0 - 0x15F0)
class UBPS26_BattlePassTileEmpty_C final : public UFortBattlePassTileBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPS26_BattlePassTileEmpty_C">();
	}
	static class UBPS26_BattlePassTileEmpty_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPS26_BattlePassTileEmpty_C>();
	}
};

}

