#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BPS26_RichTextDecorators

#include "Basic.hpp"

#include "UMG_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPS26_RichTextDecorators.BPS26_RichTextDecorators_C
// 0x0000 (0x0030 - 0x0030)
class UBPS26_RichTextDecorators_C final : public URichTextBlockImageDecorator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPS26_RichTextDecorators_C">();
	}
	static class UBPS26_RichTextDecorators_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPS26_RichTextDecorators_C>();
	}
};

}

