#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ColorBlindExtension

#include "Basic.hpp"

#include "ColorBlindExtension_classes.hpp"
#include "ColorBlindExtension_parameters.hpp"


namespace SDK
{

// Function ColorBlindExtension.ColorBlindExtension_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UColorBlindExtension_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ColorBlindExtension_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ColorBlindExtension.ColorBlindExtension_C.ExecuteUbergraph_ColorBlindExtension
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UColorBlindExtension_C::ExecuteUbergraph_ColorBlindExtension(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ColorBlindExtension_C", "ExecuteUbergraph_ColorBlindExtension");

	Params::ColorBlindExtension_C_ExecuteUbergraph_ColorBlindExtension Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ColorBlindExtension.ColorBlindExtension_C.OnSettingAssigned
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UFortSetting*                     InSetting                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UColorBlindExtension_C::OnSettingAssigned(class UFortSetting* InSetting)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ColorBlindExtension_C", "OnSettingAssigned");

	Params::ColorBlindExtension_C_OnSettingAssigned Parms{};

	Parms.InSetting = InSetting;

	UObject::ProcessEvent(Func, &Parms);
}

}

