#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: CRD_CinematicSequence

#include "Basic.hpp"


namespace SDK
{

// Enum CRD_CinematicSequence.ECinematicSequenceVisibility
// NumValues: 0x0004
enum class ECinematicSequenceVisibility : uint8
{
	InstigatorOnly                           = 0,
	InstigatingTeam                          = 1,
	Everyone                                 = 2,
	ECinematicSequenceVisibility_MAX         = 3,
};

}

