#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: EnumOptionExtension

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass EnumOptionExtension.EnumOptionExtension_C
// 0x0020 (0x02E8 - 0x02C8)
class UEnumOptionExtension_C final : public UFortSettingDetailExtension
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UDynamicEntryBox*                       EnumOptions;                                       // 0x02D0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UDynamicEntryBox*                       EnumOptions_Disabled;                              // 0x02D8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   RichText_DisabledDetails;                          // 0x02E0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_EnumOptionExtension(int32 EntryPoint);
	void OnSettingAssigned(class UFortSetting* InSetting);
	void OnSettingValueChanged(class UFortSetting* InSetting);
	void RebuildOptions(class UObject* Setting_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EnumOptionExtension_C">();
	}
	static class UEnumOptionExtension_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UEnumOptionExtension_C>();
	}
};

}

