#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: EpicMediaCDNHostnames

#include "Basic.hpp"

#include "EpicMediaCDNHostnames_classes.hpp"
#include "EpicMediaCDNHostnames_parameters.hpp"


namespace SDK
{

// Function EpicMediaCDNHostnames.EpicMediaCDNHostnames.GetSelectedHostName
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class FString UEpicMediaCDNHostnames::GetSelectedHostName()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("EpicMediaCDNHostnames", "GetSelectedHostName");

	Params::EpicMediaCDNHostnames_GetSelectedHostName Parms{};

	auto Flgs = Func->FunctionFlags;
	Func->FunctionFlags |= 0x400;

	UObject::ProcessEvent(Func, &Parms);

	Func->FunctionFlags = Flgs;

	return Parms.ReturnValue;
}

}

