#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FortMetasound

#include "Basic.hpp"


namespace SDK
{

// Enum FortMetasound.EFortAudioAffiliation
// NumValues: 0x0005
enum class EFortAudioAffiliation : uint8
{
	Local                                    = 0,
	Friendly                                 = 1,
	Enemy                                    = 2,
	Neutral                                  = 3,
	EFortAudioAffiliation_MAX                = 4,
};

}

