#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: FrontendEventNotifications

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FrontendEventNotifications.FrontendEventNotifications_C
// 0x0000 (0x03C0 - 0x03C0)
class UFrontendEventNotifications_C final : public UFortFrontendEventNotifications
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FrontendEventNotifications_C">();
	}
	static class UFrontendEventNotifications_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFrontendEventNotifications_C>();
	}
};

}

