#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GoalsRewards_Quest

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass GoalsRewards_Quest.GoalsRewards_Quest_C
// 0x0000 (0x03F8 - 0x03F8)
class UGoalsRewards_Quest_C final : public UAthenaChallengeRewards
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GoalsRewards_Quest_C">();
	}
	static class UGoalsRewards_Quest_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGoalsRewards_Quest_C>();
	}
};

}

