#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: jg_test

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class jg_test.jg_testBPLibrary
// 0x0000 (0x0028 - 0x0028)
class Ujg_testBPLibrary final : public UBlueprintFunctionLibrary
{
public:
	static float jg_testSampleFunction(float Param);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"jg_testBPLibrary">();
	}
	static class Ujg_testBPLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<Ujg_testBPLibrary>();
	}
};

}

