#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: KoalaSettingDetailExtension

#include "Basic.hpp"

#include "KoalaSettingDetailExtension_classes.hpp"
#include "KoalaSettingDetailExtension_parameters.hpp"


namespace SDK
{

// Function KoalaSettingDetailExtension.KoalaSettingDetailExtension_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UKoalaSettingDetailExtension_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KoalaSettingDetailExtension_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function KoalaSettingDetailExtension.KoalaSettingDetailExtension_C.ExecuteUbergraph_KoalaSettingDetailExtension
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKoalaSettingDetailExtension_C::ExecuteUbergraph_KoalaSettingDetailExtension(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KoalaSettingDetailExtension_C", "ExecuteUbergraph_KoalaSettingDetailExtension");

	Params::KoalaSettingDetailExtension_C_ExecuteUbergraph_KoalaSettingDetailExtension Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function KoalaSettingDetailExtension.KoalaSettingDetailExtension_C.OnConnectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bConnected                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UKoalaSettingDetailExtension_C::OnConnectionChanged(bool bConnected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("KoalaSettingDetailExtension_C", "OnConnectionChanged");

	Params::KoalaSettingDetailExtension_C_OnConnectionChanged Parms{};

	Parms.bConnected = bConnected;

	UObject::ProcessEvent(Func, &Parms);
}

}

