#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: PreferredItemSlotsExtension

#include "Basic.hpp"

#include "PreferredItemSlotsExtension_classes.hpp"
#include "PreferredItemSlotsExtension_parameters.hpp"


namespace SDK
{

// Function PreferredItemSlotsExtension.PreferredItemSlotsExtension_C.ExecuteUbergraph_PreferredItemSlotsExtension
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPreferredItemSlotsExtension_C::ExecuteUbergraph_PreferredItemSlotsExtension(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PreferredItemSlotsExtension_C", "ExecuteUbergraph_PreferredItemSlotsExtension");

	Params::PreferredItemSlotsExtension_C_ExecuteUbergraph_PreferredItemSlotsExtension Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PreferredItemSlotsExtension.PreferredItemSlotsExtension_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPreferredItemSlotsExtension_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("PreferredItemSlotsExtension_C", "PreConstruct");

	Params::PreferredItemSlotsExtension_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

