#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: SubtitleExtension

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SubtitleExtension.SubtitleExtension_C
// 0x0008 (0x02D0 - 0x02C8)
class USubtitleExtension_C final : public UFortSettingDetailExtension
{
public:
	class USubtitleDisplay*                       SubtitleDisplay;                                   // 0x02C8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SubtitleExtension_C">();
	}
	static class USubtitleExtension_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USubtitleExtension_C>();
	}
};

}

