#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: VerseSimulation_0

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// ScriptStruct VerseSimulation.LocalizableMessageParameterAgent
// 0x0030 (0x0030 - 0x0000)
struct FLocalizableMessageParameterAgent final
{
public:
	struct FUniqueNetIdRepl                       Value;                                             // 0x0000(0x0030)(HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

