#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: VkEditorContentService

#include "Basic.hpp"

#include "VkEngineTypes_structs.hpp"


namespace SDK
{

// ScriptStruct VkEditorContentService.VkContentPackageRequest
// 0x0010 (0x0078 - 0x0068)
struct FVkContentPackageRequest final : public FVkResolvedContent
{
public:
	class FString                                 ProjectID;                                         // 0x0068(0x0010)(ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};

}

